const router = require("express").Router();
const { authenticate, requirePermission } = require("../../middleware/authMiddleware");
const controller = require("../../controllers/Contabilidad/sancionesConfiguracionController");
router.use(authenticate, requirePermission("Contabilidad", "Administracion"));
router.get("/", controller.listar);
router.get("/:id", controller.obtener);
router.post("/", controller.crear);
router.put("/:id", controller.actualizar);
router.delete("/:id", controller.desactivar);
module.exports = router;
