import { useEffect, useState } from "react";
import Swal from "sweetalert2";
import * as XLSX from "xlsx";
import { Download, RefreshCw, ShieldAlert } from "lucide-react";
import { api } from "../../api/client";

const iso = (date) => date.toISOString().slice(0, 10);
const today = new Date();
const monday = new Date(today); monday.setDate(today.getDate() - ((today.getDay() + 6) % 7));
const money = new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" });

export default function SancionesVentas() {
  const [filters, setFilters] = useState({ fechaInicio: iso(monday), fechaFin: iso(today), agenciaId: "", vendedorId: "", cierreCaja: "" });
  const [agencias, setAgencias] = useState([]), [vendedores, setVendedores] = useState([]), [rows, setRows] = useState([]), [resumen, setResumen] = useState({}), [loading, setLoading] = useState(false);
  useEffect(() => { Promise.all([api.get("/agencias"), api.get("/usuarios")]).then(([a,u]) => { setAgencias(Array.isArray(a.data) ? a.data : a.data?.agencias || []); setVendedores(Array.isArray(u.data) ? u.data : u.data?.usuarios || []); }).catch(()=>{}); }, []);
  const load = async () => { setLoading(true); try { const params = Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=="")); const { data } = await api.get("/api/contabilidad/sanciones-ventas", { params }); setRows(data.data || []); setResumen(data.resumen || {}); } catch(e) { Swal.fire("Error", e.response?.data?.message || "No se pudo generar el reporte", "error"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const exportExcel = () => { const data = rows.map(r => ({ Vendedor:r.vendedor, Agencia:r.agencia, "Cargo/Rol de pago":r.cargo, "Ventas realizadas":r.unidadesVendidas, "Mínimo requerido":r.minimoUnidades, "Unidades faltantes":r.unidadesFaltantes, "Multa por unidad":r.valorMultaUnidad, "Total multa":r.multaTotal, Estado:r.aplicaSancion?"Sancionado":"Cumple", Observación:r.observacion||"" })); const ws=XLSX.utils.json_to_sheet(data); ws["!cols"]=[24,20,28,18,18,18,18,16,14,42].map(w=>({wch:w})); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,"Sanciones"); XLSX.writeFile(wb,`sanciones_ventas_${filters.fechaInicio}_${filters.fechaFin}.xlsx`); };
  return <div className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5"><section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-semibold uppercase text-rose-700"><ShieldAlert size={18}/> Contabilidad</p><h1 className="text-2xl font-bold text-slate-800">Sanciones por ventas mínimas</h1></div><button disabled={!rows.length} onClick={exportExcel} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-white disabled:opacity-50"><Download size={18}/> Exportar Excel</button></div>
    <div className="mt-5 grid gap-3 md:grid-cols-3 lg:grid-cols-6"><label className="text-xs font-medium">Desde<input type="date" value={filters.fechaInicio} onChange={e=>setFilters({...filters,fechaInicio:e.target.value})} className="mt-1 w-full rounded-lg border px-2 py-2"/></label><label className="text-xs font-medium">Hasta<input type="date" value={filters.fechaFin} onChange={e=>setFilters({...filters,fechaFin:e.target.value})} className="mt-1 w-full rounded-lg border px-2 py-2"/></label><label className="text-xs font-medium">Agencia<select value={filters.agenciaId} onChange={e=>setFilters({...filters,agenciaId:e.target.value})} className="mt-1 w-full rounded-lg border px-2 py-2"><option value="">Todas</option>{agencias.map(a=><option key={a.id} value={a.id}>{a.nombre}</option>)}</select></label><label className="text-xs font-medium">Vendedor<select value={filters.vendedorId} onChange={e=>setFilters({...filters,vendedorId:e.target.value})} className="mt-1 w-full rounded-lg border px-2 py-2"><option value="">Todos</option>{vendedores.map(v=><option key={v.id} value={v.id}>{v.nombre}</option>)}</select></label><label className="text-xs font-medium">Cierre de caja<select value={filters.cierreCaja} onChange={e=>setFilters({...filters,cierreCaja:e.target.value})} className="mt-1 w-full rounded-lg border px-2 py-2"><option value="">Todos</option><option>CONTADO</option><option>CREDITV</option><option>UPHONE</option></select></label><button onClick={load} className="mt-5 flex h-10 items-center justify-center gap-2 rounded-lg bg-slate-800 px-3 text-white"><RefreshCw size={17}/> Consultar</button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Vendedores",resumen.totalVendedores||0],["Sancionados",resumen.totalSancionados||0],["Unidades faltantes",resumen.totalUnidadesFaltantes||0],["Total multas",money.format(resumen.totalMulta||0)]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{l}</p><p className="text-2xl font-bold text-slate-800">{v}</p></div>)}</section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-100 text-left"><tr>{["Vendedor","Agencia","Cargo/Rol de pago","Ventas realizadas","Mínimo requerido","Unidades faltantes","Multa por unidad","Total multa","Estado"].map(h=><th key={h} className="whitespace-nowrap px-3 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.usuarioId}-${r.agencia}-${i}`} className="border-t"><td className="px-3 py-3 font-medium">{r.vendedor}</td><td className="px-3 py-3">{r.agencia}</td><td className="px-3 py-3"><div>{r.cargo}</div>{r.observacion&&<div className="text-xs text-amber-700">{r.observacion}</div>}</td><td className="px-3 py-3 text-center">{r.unidadesVendidas}</td><td className="px-3 py-3 text-center">{r.minimoUnidades}</td><td className="px-3 py-3 text-center">{r.unidadesFaltantes}</td><td className="px-3 py-3">{money.format(r.valorMultaUnidad)}</td><td className="px-3 py-3 font-semibold">{money.format(r.multaTotal)}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.aplicaSancion?"bg-rose-100 text-rose-700":"bg-emerald-100 text-emerald-700"}`}>{r.aplicaSancion?"Sancionado":"Cumple"}</span></td></tr>)}</tbody></table></div>{loading&&<p className="p-8 text-center">Cargando...</p>}{!loading&&!rows.length&&<p className="p-8 text-center text-slate-500">No hay vendedores para los filtros seleccionados.</p>}</section></div></div>;
}
