import { useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import { Pencil, Plus, RefreshCw, ShieldAlert, Trash2, X } from "lucide-react";
import { api } from "../../api/client";

const ENDPOINT = "/api/contabilidad/sanciones-configuracion";
const emptyForm = { rolPagoId: "", cargoReferencia: "", periodo: "SEMANAL", minimoUnidades: "", valorMultaUnidad: "", descripcion: "", activo: true };
const money = new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD" });

export default function SancionesConfiguracion() {
  const [rows, setRows] = useState([]), [roles, setRoles] = useState([]), [loading, setLoading] = useState(false);
  const [filters, setFilters] = useState({ cargo: "", periodo: "", activo: "true" });
  const [form, setForm] = useState(emptyForm), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [saving, setSaving] = useState(false);
  const params = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, v]) => v !== "")), [filters]);
  const load = async () => { setLoading(true); try { const [configs, rolesPago] = await Promise.all([api.get(ENDPOINT, { params }), api.get("/api/contabilidad/roles-pago", { params: { activo: "true" } })]); setRows(Array.isArray(configs.data) ? configs.data : []); setRoles(Array.isArray(rolesPago.data) ? rolesPago.data : []); } catch { Swal.fire("Error", "No se pudieron cargar las configuraciones", "error"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const close = () => { setOpen(false); setEditing(null); setForm(emptyForm); };
  const show = (row = null) => { setEditing(row); setForm(row ? { rolPagoId: row.rolPagoId ?? "", cargoReferencia: row.cargoReferencia, periodo: row.periodo, minimoUnidades: row.minimoUnidades, valorMultaUnidad: row.valorMultaUnidad, descripcion: row.descripcion || "", activo: row.activo } : emptyForm); setOpen(true); };
  const chooseRole = (value) => { const role = roles.find((r) => String(r.id) === value); setForm((old) => ({ ...old, rolPagoId: value, ...(role ? { cargoReferencia: role.cargo } : {}) })); };
  const save = async () => { setSaving(true); try { const payload = { ...form, rolPagoId: form.rolPagoId || null, minimoUnidades: Number(form.minimoUnidades), valorMultaUnidad: Number(form.valorMultaUnidad) }; editing ? await api.put(`${ENDPOINT}/${editing.id}`, payload) : await api.post(ENDPOINT, payload); await Swal.fire("Listo", "Configuración guardada", "success"); close(); load(); } catch (e) { Swal.fire("Error", e.response?.data?.message || "No se pudo guardar", "error"); } finally { setSaving(false); } };
  const deactivate = async (row) => { const result = await Swal.fire({ title: "Desactivar configuración", text: row.cargoReferencia, icon: "warning", showCancelButton: true, confirmButtonText: "Desactivar", cancelButtonText: "Cancelar" }); if (result.isConfirmed) { await api.delete(`${ENDPOINT}/${row.id}`); load(); } };
  return <div className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-semibold uppercase text-rose-700"><ShieldAlert size={18}/> Sanciones de ventas</p><h1 className="text-2xl font-bold text-slate-800">Configuración de mínimos</h1></div><button onClick={() => show()} className="flex items-center gap-2 rounded-lg bg-rose-600 px-4 py-2 text-white"><Plus size={18}/> Nueva configuración</button></div>
      <div className="mt-5 grid gap-3 md:grid-cols-4"><input value={filters.cargo} onChange={(e) => setFilters({...filters,cargo:e.target.value})} placeholder="Filtrar por cargo" className="rounded-lg border px-3 py-2"/><select value={filters.periodo} onChange={(e)=>setFilters({...filters,periodo:e.target.value})} className="rounded-lg border px-3 py-2"><option value="">Todos los periodos</option><option>SEMANAL</option><option>MENSUAL</option><option>RANGO</option></select><select value={filters.activo} onChange={(e)=>setFilters({...filters,activo:e.target.value})} className="rounded-lg border px-3 py-2"><option value="true">Activas</option><option value="todos">Todas</option><option value="false">Inactivas</option></select><button onClick={load} className="flex items-center justify-center gap-2 rounded-lg border px-3 py-2"><RefreshCw size={17}/> Aplicar filtros</button></div>
    </section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-100 text-left text-slate-600"><tr>{["Cargo / rol de pago","Periodo","Mínimo","Multa por unidad","Descripción","Estado","Acciones"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="px-4 py-3 font-medium">{row.rolPago?.cargo || row.cargoReferencia}</td><td className="px-4 py-3">{row.periodo}</td><td className="px-4 py-3">{row.minimoUnidades}</td><td className="px-4 py-3">{money.format(row.valorMultaUnidad)}</td><td className="px-4 py-3">{row.descripcion || "-"}</td><td className="px-4 py-3">{row.activo ? "Activa" : "Inactiva"}</td><td className="flex gap-2 px-4 py-3"><button onClick={()=>show(row)} title="Editar"><Pencil size={18}/></button>{row.activo&&<button onClick={()=>deactivate(row)} className="text-rose-600" title="Desactivar"><Trash2 size={18}/></button>}</td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<p className="p-8 text-center text-slate-500">No hay configuraciones para mostrar.</p>}{loading&&<p className="p-8 text-center">Cargando...</p>}</section>
  </div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Editar":"Nueva"} configuración</h2><button onClick={close}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Rol de pago<select value={form.rolPagoId} onChange={(e)=>chooseRole(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Referencia textual</option>{roles.map(r=><option key={r.id} value={r.id}>{r.cargo}</option>)}</select></label><label className="text-sm">Cargo de referencia<input value={form.cargoReferencia} onChange={(e)=>setForm({...form,cargoReferencia:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Periodo<select value={form.periodo} onChange={(e)=>setForm({...form,periodo:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"><option>SEMANAL</option><option>MENSUAL</option><option>RANGO</option></select></label><label className="text-sm">Mínimo de unidades<input type="number" min="0" value={form.minimoUnidades} onChange={(e)=>setForm({...form,minimoUnidades:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Multa por unidad<input type="number" min="0" step="0.01" value={form.valorMultaUnidad} onChange={(e)=>setForm({...form,valorMultaUnidad:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm sm:col-span-2">Descripción<textarea value={form.descripcion} onChange={(e)=>setForm({...form,descripcion:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label></div><div className="mt-5 flex justify-end gap-3"><button onClick={close} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={saving} onClick={save} className="rounded-lg bg-rose-600 px-4 py-2 text-white disabled:opacity-50">{saving?"Guardando...":"Guardar"}</button></div></div></div>}</div>;
}
