export const CONDICIONES_PLAN_BATALLA = {
  inexistencia: {
    label: "Inexistencia",
    formula: [
      "ENCUENTRE UNA LÍNEA DE COMUNICACIÓN",
      "DESE A CONOCER",
      "DESCUBRA LO QUE NECESITA O DESEA",
      "HÁGALO, PRODUZCALO O PRESÉNTELO",
    ],
  },
  inexistencia_extendida: {
    label: "Inexistencia Extendida",
    formula: [
      "ENCUENTRA Y PONTE EN LÍNEA DE COMUNICACIÓN QUE VAYAS A NECESITAR PARA DAR Y OBTENER INFORMACIÓN RELATIVA A TUS DEBERES Y SUMINISTROS",
      "DATE A CONOCER, JUNTO CON LA DESIGNACIÓN DE TU PUESTO Y TUS DEBERES, A TODOS LOS TERMINALES QUE NECESITARÁS PARA LA OBTENCIÓN DE INFORMACIÓN Y LA ENTREGA DE DATOS",
      "DESCUBRE DE TUS SUPERIORES, COMPAÑEROS DE TRABAJO Y CUALQUIER PÚBLICO CON EL QUE PUEDAS NECESITAR PONERTE EN CONTACTO EN EL CUMPLIMIENTO DE TUS OBLIGACIONES, LO QUE CADA UNO DE ELLOS NECESITA Y DESEA",
      "HAZ, PRODUCE Y PRESENTA LO QUE CADA UNO NECESITA Y DESEA, QUE ESTÉ EN CONFORMIDAD A LA POLÍTICA",
      "MANTÉN LAS LÍNEAS DE COMUNICACIÓN QUE TIENES Y AMPLÍALAS PARA OBTENER OTRA INFORMACIÓN QUE AHORA ENCUENTRES QUE NECESITAS DE MANERA HABITUAL",
      "MANTÉN TUS LÍNEAS DE ORIGINACIÓN PARA INFORMAR A OTROS DE LO QUE ESTÁS HACIENDO EXACTAMENTE, PERO SOLO A AQUELLOS QUE REALMENTE NECESITAN LA INFORMACIÓN",
      "SIMPLIFICA Y HAZ DE FORMA MÁS EFICIENTE LO QUE ESTÁS HACIENDO, PRODUCIÉNDOLO Y PRESENTÁNDOLO DE MODO QUE SE ACERQUE MÁS A LO QUE REALMENTE SE NECESITA Y SE DESEA",
      "DANDO Y RECIBIENDO INFORMACIÓN PLENA RESPECTO A TUS PRODUCTOS, HAZ, PRODUCE Y PRESENTA, DE MANERA HABITUAL EN TU PUESTO, UN PRODUCTO MEJOR",
    ],
  },
  peligro: {
    label: "Peligro",
    formula: [
      "PASE POR ALTO HÁBITOS O RUTINAS NORMALES",
      "RESUELVA LA SITUACIÓN Y CUALQUIER PELIGRO QUE HAYA EN ELLA",
      "ASIGNESE UNA CONDICIÓN DE PELIGRO",
      "DESCUBRA QUÉ ESTÁ HACIENDO CONTRARIO A LOS IDEALES O A LOS MEJORES INTERESES DEL GRUPO O ACTIVIDAD Y USE AUTODISCIPLINA PARA CORREGIRLO Y VUÉLVASE HONESTO Y RETO",
      "REORGANICE SU VIDA PARA QUE LA SITUACIÓN PELIGROSA NO LE ESTÉ OCURRIENDO CONTINUAMENTE",
      "FORMULE Y ADOPTE UNA POLÍTICA FIRME QUE DE AQUÍ EN ADELANTE DETECTE LA MISMA SITUACIÓN E IMPIDE QUE VUELVA A OCURRIR",
    ],
  },
  emergencia: {
    label: "Emergencia",
    formula: [
      "PROMOCIONA Y PRODUCE",
      "CAMBIE SU FORMA DE ACTUAR",
      "ECONOMICE",
      "PREPARARSE PARA DAR SERVICIO",
      "HACER MÁS ESTRICTA LA DISCIPLINA",
    ],
  },
  normal: {
    label: "Normal",
    formula: [
      "NO CAMBIAR NADA",
      "LA ÉTICA ES MUY POCO SEVERA",
      "SI UNA ESTADÍSTICA MEJORA, EXAMINALA Y AVERIGUA QUE MEJORÓ SIN ABANDONAR LO QUE ESTABAS HACIENDO ANTES",
      "ENCUENTRA POR QUE EMPEORO UNA ESTADÍSTICA Y CORRÍGELO",
    ],
  },
  afluencia: {
    label: "Afluencia",
    formula: [
      "ECONOMIZA EN ACTIVIDADES INNECESARIAS QUE NO CONTRIBUYERON A LA AFLUENCIA",
      "HAZ QUE TODA ACCIÓN CUENTE Y NO TOMES PARTE EN NINGUNA ACCIÓN INÚTIL",
      "CONSOLIDAR LAS GANANCIAS, EN CUALQUIER ÁREA EN QUE HAYAS OBTENIDO UNA GANANCIA, LA CONSERVAS",
      "DESCUBRE POR TI MISMO Y PARA TI MISMO QUE CAUSÓ LA CONDICIÓN DE AFLUENCIA Y REFUERZALO",
    ],
  },
};

export const BLOQUES_PLAN_BATALLA = [
  "Actividades urgentes",
  "Actividades pendientes",
  "Ordenes que debo cumplir",
  "Ordenes que deben realizar mis juniors",
  "Meta para la semana",
  "Objetivos que contribuyen al plan estrategico",
];
