server {
    listen 80 default_server;
    server_name www.creditek-ecuador.com _;

    root /usr/share/nginx/html;
    index index.html;

    location = /robots.txt {
        default_type text/plain;
        try_files $uri =404;
    }

    location = /sitemap.xml {
        default_type application/xml;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name creditek-ecuador.com;

    return 301 https://www.creditek-ecuador.com$request_uri;
}
