const express = require("express");
const controller = require("../../controllers/GHL/repartoOportunidadesController");
const { authenticate, requirePermission } = require("../../middleware/authMiddleware");
const router = express.Router();
router.use(authenticate, requirePermission("Gerencia", "Administracion", "Sistemas"));
router.get("/catalogos/pipelines", controller.pipelines);
router.get("/catalogos/pipelines/:pipelineId/stages", controller.stages);
router.get("/catalogos/users", controller.users);
router.get("/configuraciones", controller.list);
router.get("/configuraciones/:id", controller.get);
router.post("/configuraciones", controller.create);
router.put("/configuraciones/:id", controller.update);
router.patch("/configuraciones/:id/estado", controller.state);
router.post("/configuraciones/:id/preview", controller.preview);
router.post("/configuraciones/:id/execute", controller.execute);
router.get("/ejecuciones", controller.history);
router.get("/ejecuciones/:id", controller.execution);
router.post("/ejecuciones/:id/pause", controller.pause);
router.post("/ejecuciones/:id/resume", controller.resume);
router.post("/ejecuciones/:id/cancel", controller.cancel);
router.post("/ejecuciones/:id/force-finish-stale", controller.forceFinishStale);
module.exports = router;
